version: '3'
networks:
  rb-test:
services:
  php:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: php-rb-test
    ports:
      - ${PHP_PORT}:9000
    networks:
      - rb-test
    volumes:
      - ./../app:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
  mysql:
    container_name: mysqlrb-test
    image: mysql:5.7.22
    networks:
      - rb-test
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: rb-test
      MYSQL_USER: user
      MYSQL_PASSWORD: 111111
      MYSQL_ROOT_PASSWORD: 222222
  nginx:
    container_name: nginx-rb-test
    image: nginx:stable-alpine
    ports:
      - ${NGINX_PORT}:80
    networks:
      - rb-test
    depends_on:
      - php
      - mysql
    volumes:
      - ./../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  phpmyadmin:
    container_name: phpmyadmin-rb-test
    image: phpmyadmin
    depends_on:
      - mysql
    networks:
      - rb-test
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 222222
